Update cicd-workflow.yml

diff --git a/.github/workflows/cicd-workflow.yml b/.github/workflows/cicd-workflow.yml
--- a/.github/workflows/cicd-workflow.yml
+++ b/.github/workflows/cicd-workflow.yml
@@ -24,6 +24,23 @@ jobs:
     needs: build
     runs-on: [self-hosted, Linux, X64]
     steps:
+      - name: Check if Docker is installed
+        run: |
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found! Installing..."
+            sudo apt update
+            sudo apt install -y docker.io
+            sudo systemctl start docker
+            sudo systemctl enable docker
+          else
+            echo "Docker is already installed!"
+          fi
+          docker --version
+
+      - name: Login to Docker Hub
+        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+
       - name: Pull image from Docker Hub
         run: docker pull ${{ secrets.DOCKER_USERNAME }}/testcrud:latest
 
